#!/bin/bash
laptop="laptop"
home="home"
work="work"
input=$(echo -e "${laptop}\n${home}\n${work}" | dmenu)
case $input in
$laptop)
  echo "laptop"
  xrandr --output DP2-1 --off --output DP2-2 --off  --output DP2-3 --off --output eDP1 --auto
  ;;
$home)
  echo "home"
  xrandr --output HDMI2 --right-of eDP1 --auto
  ;;
$work)
  echo "work"
  setxkbmap se -option caps:escape 
  xrandr --output eDP1 --off --output DP2-1 --primary --auto --output DP2-2 --left-of DP2-1 --auto --output DP2-3 --right-of DP2-1 --rotate left --auto
  ;;
esac
